name: Test on push

on:
  push:
    branches: master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"

    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: master

    - name: Test
      run: python3 check.py
      env:
        POST_TOKEN: ${{secrets.GITHUB_TOKEN}}
